# Generated by Django 5.1.4 on 2024-12-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariantmodel',
            name='variant',
        ),
        migrations.AddField(
            model_name='itemvariantmodel',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='api.itemmodel'),
        ),
    ]
