# Generated by Django 5.1.4 on 2024-12-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_itemvariantmodel_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='table_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
