# Generated by Django 5.1.4 on 2025-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ordermodel_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='serving_mode',
            field=models.CharField(choices=[('Dine in', 'Dine in'), ('Takeaway', 'Takeaway')], default='Dine in', max_length=50),
        ),
    ]
