# Generated by Django 5.1.4 on 2025-01-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ordermodel_serving_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='order_item_status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Canceled', 'Canceled')], default='Confirmed', max_length=30),
        ),
    ]
